// Generated by scripts/optimize-images.ts — do not edit by hand.
// Each entry describes the AVIF/WebP variants under /public/img/<name>-<width>.{avif,webp}.
export type OptimizedImage = {
  name: string;
  /** Intrinsic size of the largest variant (used for width/height to avoid layout shift). */
  width: number;
  height: number;
  /** Available variant widths, ascending. */
  widths: number[];
};

export const IMAGES = {
  "bridal-between-still": { name: "bridal-between-still", width: 996, height: 1580, widths: [480, 800, 996] },
  "bridal-cta-eucalyptus": { name: "bridal-cta-eucalyptus", width: 1003, height: 1568, widths: [480, 800, 1003] },
  "bridal-hero-atmosphere": { name: "bridal-hero-atmosphere", width: 992, height: 1586, widths: [480, 800, 992] },
  "bridal-just-married": { name: "bridal-just-married", width: 1003, height: 1568, widths: [480, 800, 1003] },
  "bridal-nails": { name: "bridal-nails", width: 896, height: 1200, widths: [480, 800, 896] },
  "bridal-trial-still": { name: "bridal-trial-still", width: 1003, height: 1568, widths: [480, 800, 1003] },
  "careers-hero-desktop": { name: "careers-hero-desktop", width: 1672, height: 941, widths: [480, 800, 1200, 1600, 1672] },
  "careers-hero-mobile": { name: "careers-hero-mobile", width: 1122, height: 1402, widths: [480, 800, 1122] },
  "faq-hero-desktop": { name: "faq-hero-desktop", width: 1672, height: 940, widths: [480, 800, 1200, 1600, 1672] },
  "faq-hero-mobile": { name: "faq-hero-mobile", width: 753, height: 941, widths: [480, 753] },
  "faq-hygiene-products": { name: "faq-hygiene-products", width: 1536, height: 1024, widths: [480, 800, 1200, 1536] },
  "nail-library": { name: "nail-library", width: 1080, height: 1920, widths: [480, 800, 1080] },
  "nail-slide-1": { name: "nail-slide-1", width: 928, height: 1152, widths: [480, 800, 928] },
  "nail-slide-2": { name: "nail-slide-2", width: 896, height: 1200, widths: [480, 800, 896] },
  "nail-slide-3": { name: "nail-slide-3", width: 928, height: 1152, widths: [480, 800, 928] },
  "nail-slide-4": { name: "nail-slide-4", width: 896, height: 1200, widths: [480, 800, 896] },
  "nail-slide-5": { name: "nail-slide-5", width: 848, height: 1264, widths: [480, 800, 848] },
  "proof-day1": { name: "proof-day1", width: 1080, height: 1920, widths: [480, 800, 1080] },
  "proof-day14": { name: "proof-day14", width: 1080, height: 1920, widths: [480, 800, 1080] },
  "proof-day7": { name: "proof-day7", width: 1536, height: 1920, widths: [480, 800, 1200, 1536] },
  "services-cta": { name: "services-cta", width: 1448, height: 814, widths: [480, 800, 1200, 1448] },
  "services-hero-desktop": { name: "services-hero-desktop", width: 1122, height: 1402, widths: [480, 800, 1122] },
  "services-hero-mobile": { name: "services-hero-mobile", width: 1122, height: 1402, widths: [480, 800, 1122] },
  "services-manicures": { name: "services-manicures", width: 1536, height: 1024, widths: [480, 800, 1200, 1536] },
  "services-nails": { name: "services-nails", width: 1536, height: 1024, widths: [480, 800, 1200, 1536] },
  "services-pedicures": { name: "services-pedicures", width: 1536, height: 1024, widths: [480, 800, 1200, 1536] },
  "standard-hero-salon-table": { name: "standard-hero-salon-table", width: 1122, height: 1402, widths: [480, 800, 1122] },
  "standard-products": { name: "standard-products", width: 1536, height: 1024, widths: [480, 800, 1200, 1536] },
  "standard-tray": { name: "standard-tray", width: 1122, height: 1402, widths: [480, 800, 1122] },
} as const satisfies Record<string, OptimizedImage>;

export type ImageName = keyof typeof IMAGES;
