// Regenerates the responsive AVIF/WebP variants in /public/img from the
// originals uploaded to Lovable (listed in src/assets/*.asset.json), and
// rewrites the manifest in src/lib/images.ts that <Img> reads.
//
// Run from the repo root:
//   cd scripts && bun install && bun optimize-images.ts
//
// Add a new photo by uploading it in Lovable (which creates the .asset.json),
// re-running this script, then using IMAGES["<file name without extension>"]
// with the <Img> component. Sharp lives in scripts/package.json so the site
// itself has no image-processing dependency.
import sharp from "sharp";
import { readdirSync, mkdirSync } from "fs";

const ROOT = `${import.meta.dir}/..`;
const ASSETS = `${ROOT}/src/assets`;
const OUT = `${ROOT}/public/img`;
const MANIFEST = `${ROOT}/src/lib/images.ts`;
// Originals are only served from the published site, not from the repo.
const ORIGIN = "https://belleva-design-library.lovable.app";
const WIDTHS = [480, 800, 1200, 1600];
// Uploaded but not used anywhere on the site.
const SKIP = new Set(["bridal-hero.png", "standard-hero-fabric.png", "tray-photo.png", "standard-founder-desk.png"]);
// Full-bleed desktop photos whose originals are narrower than the screens they fill.
// We pre-upscale these with Lanczos + light sharpening (much crisper than the browser's
// own stretch) into a separate "<name>-hd" entry, used above 768px only.
const HD_WIDTHS: Record<string, number[]> = {
  "nail-library": [1440, 1920, 2560],
};

mkdirSync(OUT, { recursive: true });

type Entry = { name: string; width: number; height: number; widths: number[] };
const manifest: Entry[] = [];

for (const file of readdirSync(ASSETS).filter((f) => f.endsWith(".asset.json")).sort()) {
  const original = file.replace(/\.asset\.json$/, "");
  if (SKIP.has(original)) continue;
  const { url } = await Bun.file(`${ASSETS}/${file}`).json();
  const buf = Buffer.from(await (await fetch(`${ORIGIN}${url}`)).arrayBuffer());
  const name = original.replace(/\.(png|jpe?g)$/i, "");
  const meta = await sharp(buf).rotate().metadata();
  const srcW = meta.width!, srcH = meta.height!;
  const widths = [...WIDTHS.filter((w) => w < srcW), srcW];
  let bytes = 0;
  for (const w of widths) {
    const resized = sharp(buf).rotate().resize({ width: w, withoutEnlargement: true });
    const avif = await resized.clone().avif({ quality: 55, effort: 4 }).toFile(`${OUT}/${name}-${w}.avif`);
    const webp = await resized.clone().webp({ quality: 80 }).toFile(`${OUT}/${name}-${w}.webp`);
    bytes += avif.size + webp.size;
  }
  manifest.push({ name, width: srcW, height: srcH, widths });
  console.log(`${name}: ${srcW}x${srcH} -> ${widths.join("/")} (${(bytes / 1024).toFixed(0)} KB all variants, original ${(buf.byteLength / 1024).toFixed(0)} KB)`);

  const hdWidths = HD_WIDTHS[name];
  if (hdWidths) {
    const hdName = `${name}-hd`;
    let hdBytes = 0;
    for (const w of hdWidths) {
      const upscaled = sharp(buf)
        .rotate()
        .resize({ width: w, kernel: "lanczos3" })
        .sharpen({ sigma: 0.9, m1: 0.6, m2: 2.2 });
      const avif = await upscaled.clone().avif({ quality: 70, effort: 5 }).toFile(`${OUT}/${hdName}-${w}.avif`);
      const webp = await upscaled.clone().webp({ quality: 88 }).toFile(`${OUT}/${hdName}-${w}.webp`);
      hdBytes += avif.size + webp.size;
    }
    const top = hdWidths.at(-1)!;
    manifest.push({ name: hdName, width: top, height: Math.round((srcH * top) / srcW), widths: hdWidths });
    console.log(`${hdName}: -> ${hdWidths.join("/")} (${(hdBytes / 1024).toFixed(0)} KB all variants)`);
  }
}

await Bun.write(
  MANIFEST,
  `// Generated by scripts/optimize-images.ts — do not edit by hand.
// Each entry describes the AVIF/WebP variants under /public/img/<name>-<width>.{avif,webp}.
export type OptimizedImage = {
  name: string;
  /** Intrinsic size of the largest variant (used for width/height to avoid layout shift). */
  width: number;
  height: number;
  /** Available variant widths, ascending. */
  widths: number[];
};

export const IMAGES = {
${manifest.map((m) => `  "${m.name}": { name: "${m.name}", width: ${m.width}, height: ${m.height}, widths: [${m.widths.join(", ")}] },`).join("\n")}
} as const satisfies Record<string, OptimizedImage>;

export type ImageName = keyof typeof IMAGES;
`,
);
console.log(`wrote ${manifest.length} entries to src/lib/images.ts`);
